name: Playwright Tests
on:
  push:
    branches: [ main, master, staging ]
  pull_request:
    branches: [ main, master, staging ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
      working-directory: ./interface
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      working-directory: ./interface
    - name: Run Playwright tests
      run: npx playwright test
      working-directory: ./interface
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
